### ISSUE TITLE
Code review  

### ISSUE THREAD

**Issue by jlberbesi** [Jrmcuervo/To-do-list#1]
Great work so far.  However I would like to highlight the following aspects below:

- Kindly, update the README file with information related to the project you are currently working on.

Also, 

@Javed-Shahbaz: -Good effort in setting up the webpack configuration.

**Comment by LarryIVC** [comment]
Hi @Jrmcuervo, Good job configuring `Webpack`. 👍 
You could consider in the` .gitignore `file, to mark an entry as a `folder`, put the symbol `"/"` at the end of the name to differentiate it from a `file`.
say:
`node_modules`
consider to change
`node_modules/`

Otherwise everything looks great. 👏 
Happy coding 😄
